<a href="https://colab.research.google.com/github/rudramadhabofficial/DeepLearningLabAssignment1/blob/main/dl_ass2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# McCulloch-Pitts Neuron for AND Gate

def mp_and_gate(x1, x2):
    # Weights
    w1 = 1
    w2 = 1

    # Threshold
    theta = 2

    # Weighted sum
    weighted_sum = w1 * x1 + w2 * x2

    # Activation function (step function)
    if weighted_sum >= theta:
        return 1
    else:
        return 0


# Testing the AND gate
inputs = [(0,0), (0,1), (1,0), (1,1)]

print("x1 x2 -> Output")
for x1, x2 in inputs:
    print(x1, x2, "->", mp_and_gate(x1, x2))


x1 x2 -> Output
0 0 -> 0
0 1 -> 0
1 0 -> 0
1 1 -> 1


In [2]:
# McCulloch-Pitts Neuron for OR Gate

def mp_or_gate(x1, x2):
    # Weights
    w1 = 1
    w2 = 1

    # Threshold
    theta = 1

    # Weighted sum
    weighted_sum = w1 * x1 + w2 * x2

    # Step activation function
    if weighted_sum >= theta:
        return 1
    else:
        return 0


# Testing the OR gate
inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]

print("x1 x2 -> Output")
for x1, x2 in inputs:
    print(x1, x2, "->", mp_or_gate(x1, x2))


x1 x2 -> Output
0 0 -> 0
0 1 -> 1
1 0 -> 1
1 1 -> 1


In [3]:
# McCulloch-Pitts Neuron for NAND Gate

def mp_nand_gate(x1, x2):
    # Weights
    w1 = -1
    w2 = -1

    # Threshold
    theta = -1

    # Weighted sum
    weighted_sum = w1 * x1 + w2 * x2

    # Step activation function
    if weighted_sum >= theta:
        return 1
    else:
        return 0


# Testing the NAND gate
inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]

print("x1 x2 -> Output")
for x1, x2 in inputs:
    print(x1, x2, "->", mp_nand_gate(x1, x2))


x1 x2 -> Output
0 0 -> 1
0 1 -> 1
1 0 -> 1
1 1 -> 0


In [4]:
# McCulloch-Pitts Neuron for NOR Gate

def mp_nor_gate(x1, x2):
    # Weights
    w1 = -1
    w2 = -1

    # Threshold
    theta = 0

    # Weighted sum
    weighted_sum = w1 * x1 + w2 * x2

    # Step activation function
    if weighted_sum >= theta:
        return 1
    else:
        return 0


# Testing the NOR gate
inputs = [(0, 0), (0, 1), (1, 0), (1, 1)]

print("x1 x2 -> Output")
for x1, x2 in inputs:
    print(x1, x2, "->", mp_nor_gate(x1, x2))


x1 x2 -> Output
0 0 -> 1
0 1 -> 0
1 0 -> 0
1 1 -> 0


In [5]:
# McCulloch-Pitts Neuron for NOT Gate

def mp_not_gate(x):
    # Weight
    w = -1

    # Threshold
    theta = 0

    # Weighted sum
    weighted_sum = w * x

    # Step activation function
    if weighted_sum >= theta:
        return 1
    else:
        return 0


# Testing the NOT gate
inputs = [0, 1]

print("x -> Output")
for x in inputs:
    print(x, "->", mp_not_gate(x))


x -> Output
0 -> 1
1 -> 0


In [6]:
# McCulloch-Pitts Neuron for AND-NOT Gate (x1 AND NOT x2)

def mp_and_not_gate(x1, x2):
    # Weights
    w1 = 1     # excitatory
    w2 = -1    # inhibitory

    # Threshold
    theta = 1

    # Weighted sum
    weighted_sum = w1 * x1 + w2 * x2

    # Step activation function
    if weighted_sum >= theta:
        return 1
    else:
        return 0


# Testing the AND-NOT gate
inputs = [(0,0), (0,1), (1,0), (1,1)]

print("x1 x2 -> Output")
for x1, x2 in inputs:
    print(x1, x2, "->", mp_and_not_gate(x1, x2))


x1 x2 -> Output
0 0 -> 0
0 1 -> 0
1 0 -> 1
1 1 -> 0


In [7]:
class MPNeuron:
    def __init__(self, weights, threshold):
        self.weights = weights
        self.threshold = threshold

    def activate(self, inputs):
        net_input = sum(w * x for w, x in zip(self.weights, inputs))
        return 1 if net_input >= self.threshold else 0


# Given data
w1 = 1
w2 = 1
theta = 2
x1 = 1
x2 = 0

# Create MP neuron
mp_neuron = MPNeuron(weights=[w1, w2], threshold=theta)

# Compute output
output = mp_neuron.activate([x1, x2])

# Display result
print("Given values:")
print(f"x1 = {x1}, x2 = {x2}")
print(f"w1 = {w1}, w2 = {w2}")
print(f"Threshold (θ) = {theta}")

print("\nNet input =", w1*x1 + w2*x2)
print("AND gate output =", output)


Given values:
x1 = 1, x2 = 0
w1 = 1, w2 = 1
Threshold (θ) = 2

Net input = 1
AND gate output = 0


In [8]:
class MPNeuron:
    def __init__(self, weights, threshold):
        self.weights = weights
        self.threshold = threshold

    def activate(self, inputs):
        net_input = sum(w * x for w, x in zip(self.weights, inputs))
        return 1 if net_input >= self.threshold else 0


# Given data for OR gate
w1 = 1
w2 = 1
theta = 1
x1 = 1
x2 = 0

# Create MP neuron
mp_neuron = MPNeuron(weights=[w1, w2], threshold=theta)

# Compute output
output = mp_neuron.activate([x1, x2])

# Display result
print("Given values:")
print(f"x1 = {x1}, x2 = {x2}")
print(f"w1 = {w1}, w2 = {w2}")
print(f"Threshold (θ) = {theta}")

print("\nNet input =", w1*x1 + w2*x2)
print("OR gate output =", output)


Given values:
x1 = 1, x2 = 0
w1 = 1, w2 = 1
Threshold (θ) = 1

Net input = 1
OR gate output = 1


In [9]:
class MPNeuron:
    def __init__(self, weights, threshold):
        self.weights = weights
        self.threshold = threshold

    def activate(self, inputs):
        net_input = sum(w * x for w, x in zip(self.weights, inputs))
        return 1 if net_input >= self.threshold else 0


# Given data for NAND gate
w1 = -1
w2 = -1
theta = -1
x1 = 0
x2 = 1

# Create MP neuron
mp_neuron = MPNeuron(weights=[w1, w2], threshold=theta)

# Compute output
output = mp_neuron.activate([x1, x2])

# Display result
print("Given values:")
print(f"x1 = {x1}, x2 = {x2}")
print(f"w1 = {w1}, w2 = {w2}")
print(f"Threshold (θ) = {theta}")

print("\nNet input =", w1*x1 + w2*x2)
print("NAND gate output =", output)


Given values:
x1 = 0, x2 = 1
w1 = -1, w2 = -1
Threshold (θ) = -1

Net input = -1
NAND gate output = 1


In [10]:
class MPNeuron:
    def __init__(self, weights, threshold):
        self.weights = weights
        self.threshold = threshold

    def activate(self, inputs):
        net_input = sum(w * x for w, x in zip(self.weights, inputs))
        return 1 if net_input >= self.threshold else 0


# Given data for NOR gate
w1 = -1
w2 = -1
theta = 0
x1 = 1
x2 = 1

# Create MP neuron
mp_neuron = MPNeuron(weights=[w1, w2], threshold=theta)

# Compute output
output = mp_neuron.activate([x1, x2])

# Display result
print("Given values:")
print(f"x1 = {x1}, x2 = {x2}")
print(f"w1 = {w1}, w2 = {w2}")
print(f"Threshold (θ) = {theta}")

print("\nNet input =", w1*x1 + w2*x2)
print("NOR gate output =", output)


Given values:
x1 = 1, x2 = 1
w1 = -1, w2 = -1
Threshold (θ) = 0

Net input = -2
NOR gate output = 0


In [11]:
class MPNeuron:
    def __init__(self, weights, threshold):
        self.weights = weights
        self.threshold = threshold

    def activate(self, inputs):
        net_input = sum(w * x for w, x in zip(self.weights, inputs))
        return 1 if net_input >= self.threshold else 0


# Given data for NOT gate
w = 1
theta = 0
x1 = 1

# Create MP neuron
mp_neuron = MPNeuron(weights=[w], threshold=theta)

# Compute output
output = mp_neuron.activate([x1])

# Display result
print("Given values:")
print(f"x1 = {x1}")
print(f"w = {w}")
print(f"Threshold (θ) = {theta}")

print("\nNet input =", w * x1)
print("NOT gate output =", output)


Given values:
x1 = 1
w = 1
Threshold (θ) = 0

Net input = 1
NOT gate output = 1


In [12]:
class MPNeuron:
    def __init__(self, weights, threshold):
        self.weights = weights
        self.threshold = threshold

    def activate(self, inputs):
        net_input = sum(w * x for w, x in zip(self.weights, inputs))
        return 1 if net_input >= self.threshold else 0


# Given data for AND-NOT gate
w1 = 1
w2 = -1
theta = 1
x1 = 1
x2 = 1

# Create MP neuron
mp_neuron = MPNeuron(weights=[w1, w2], threshold=theta)

# Compute output
output = mp_neuron.activate([x1, x2])

# Display result
print("Given values:")
print(f"x1 = {x1}, x2 = {x2}")
print(f"w1 = {w1}, w2 = {w2}")
print(f"Threshold (θ) = {theta}")

print("\nNet input =", w1*x1 + w2*x2)
print("AND-NOT gate output =", output)


Given values:
x1 = 1, x2 = 1
w1 = 1, w2 = -1
Threshold (θ) = 1

Net input = 0
AND-NOT gate output = 0


## using tensor flow and mp neurons

In [13]:
import tensorflow as tf

# Inputs for AND gate
X = tf.constant([[0., 0.],
                 [0., 1.],
                 [1., 0.],
                 [1., 1.]])

# Weights and threshold (MP neuron)
W = tf.constant([[1.],
                 [1.]])
theta = 2.0

# Weighted sum
net = tf.matmul(X, W)

# Step activation function
output = tf.cast(net >= theta, tf.int32)

print("Inputs:\n", X.numpy())
print("AND Gate Output:\n", output.numpy())


Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
AND Gate Output:
 [[0]
 [0]
 [0]
 [1]]


In [14]:
import tensorflow as tf

# Inputs for OR gate
X = tf.constant([[0., 0.],
                 [0., 1.],
                 [1., 0.],
                 [1., 1.]])

# Weights and threshold (MP neuron)
W = tf.constant([[1.],
                 [1.]])
theta = 1.0

# Weighted sum
net = tf.matmul(X, W)

# Step activation function
output = tf.cast(net >= theta, tf.int32)

print("OR Gate Output:")
print(output.numpy())


OR Gate Output:
[[0]
 [1]
 [1]
 [1]]


In [15]:
import tensorflow as tf

X = tf.constant([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
W = tf.constant([[-1.],[-1.]])
theta = -1.0

output = tf.cast(tf.matmul(X, W) >= theta, tf.int32)
print("NAND Output:\n", output.numpy())


NAND Output:
 [[1]
 [1]
 [1]
 [0]]


In [16]:
import tensorflow as tf

X = tf.constant([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
W = tf.constant([[-1.],[-1.]])
theta = 0.0

output = tf.cast(tf.matmul(X, W) >= theta, tf.int32)
print("NOR Output:\n", output.numpy())


NOR Output:
 [[1]
 [0]
 [0]
 [0]]


In [17]:
import tensorflow as tf

X = tf.constant([[0.],[1.]])
W = tf.constant([[-1.]])
theta = 0.0

output = tf.cast(tf.matmul(X, W) >= theta, tf.int32)
print("NOT Output:\n", output.numpy())


NOT Output:
 [[1]
 [0]]


In [18]:
import tensorflow as tf

X = tf.constant([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
W = tf.constant([[1.],[-1.]])
theta = 1.0

output = tf.cast(tf.matmul(X, W) >= theta, tf.int32)
print("AND-NOT Output:\n", output.numpy())


AND-NOT Output:
 [[0]
 [0]
 [1]
 [0]]
