<a href="https://colab.research.google.com/github/rudramadhabofficial/DeepLearningLabAssignment1/blob/main/dlass1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Scalar and Vector Multiplication

In [3]:
import tensorflow as tf

# Scalar
scalar = tf.constant(5, dtype=tf.float32) # Changed to float32

# Vector
vector = tf.constant([1, 2, 3], dtype=tf.float32)

# Scalar-Vector Multiplication
result = scalar * vector

print("Vector:", vector.numpy())
print("Scalar:", scalar.numpy())
print("Scalar * Vector:", result.numpy())

Vector: [1. 2. 3.]
Scalar: 5.0
Scalar * Vector: [ 5. 10. 15.]


# 2. Matrix Addition, Subtraction, and Multiplication

In [4]:
import tensorflow as tf

# Define two matrices
A = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6], [7, 8]], dtype=tf.float32)

# Matrix Addition
addition = tf.add(A, B)

# Matrix Subtraction
subtraction = tf.subtract(A, B)

# Matrix Multiplication
multiplication = tf.matmul(A, B)

print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())
print("A + B:\n", addition.numpy())
print("A - B:\n", subtraction.numpy())
print("A * B:\n", multiplication.numpy())


Matrix A:
 [[1. 2.]
 [3. 4.]]
Matrix B:
 [[5. 6.]
 [7. 8.]]
A + B:
 [[ 6.  8.]
 [10. 12.]]
A - B:
 [[-4. -4.]
 [-4. -4.]]
A * B:
 [[19. 22.]
 [43. 50.]]


## 3. Matrix Inverse and Transpose

In [5]:
import tensorflow as tf

# Define a square matrix
A = tf.constant([[4, 7], [2, 6]], dtype=tf.float32)

# Transpose
transpose = tf.transpose(A)

# Inverse
inverse = tf.linalg.inv(A)

print("Matrix A:\n", A.numpy())
print("Transpose of A:\n", transpose.numpy())
print("Inverse of A:\n", inverse.numpy())


Matrix A:
 [[4. 7.]
 [2. 6.]]
Transpose of A:
 [[4. 2.]
 [7. 6.]]
Inverse of A:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


## 4. Eigenvalues and Eigenvectors

In [6]:
import tensorflow as tf

# Define a square matrix
A = tf.constant([[2, 1], [1, 2]], dtype=tf.float32)

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eig(A)

print("Matrix A:\n", A.numpy())
print("Eigenvalues:\n", eigenvalues.numpy())
print("Eigenvectors:\n", eigenvectors.numpy())


Matrix A:
 [[2. 1.]
 [1. 2.]]
Eigenvalues:
 [2.9999998 +0.j 0.99999994+0.j]
Eigenvectors:
 [[ 0.7071068+0.j -0.7071068+0.j]
 [ 0.7071068+0.j  0.7071068+0.j]]


## 5. Check Orthogonality of a Matrix

In [7]:
import tensorflow as tf

# Define an orthogonal matrix
A = tf.constant([[0, -1], [1, 0]], dtype=tf.float32)

# Compute A^T * A
product = tf.matmul(tf.transpose(A), A)

# Identity matrix
identity = tf.eye(A.shape[0])

# Check orthogonality
is_orthogonal = tf.reduce_all(tf.abs(product - identity) < 1e-5)

print("Matrix A:\n", A.numpy())
print("A^T * A:\n", product.numpy())
print("Is Orthogonal:", is_orthogonal.numpy())


Matrix A:
 [[ 0. -1.]
 [ 1.  0.]]
A^T * A:
 [[1. 0.]
 [0. 1.]]
Is Orthogonal: True
